osx_image: xcode9
language: objective-c
sudo: required
env:
  global:
    - WORKSPACE="Umbrella.xcworkspace"
    - SCHEME="Umbrella-Package"
    - IOS_SDK="iphonesimulator11.0"
    - MACOS_SDK="macosx10.13"
    - TVOS_SDK="appletvsimulator11.0"
    - FRAMEWORK="Umbrella"
  matrix:
    - SDK="$IOS_SDK"      DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.0"

install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - swift --version

before_script:
  - set -o pipefail
  - pod repo update
  - make project

script:
  - xcodebuild clean build test
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    -enableCodeCoverage YES
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - pod lib lint --allow-warnings

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Umbrella' -X xcodeplist
